/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Estrella;

import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author Ferna
 */
public class EstrellaEnEstrella extends javax.swing.JFrame{
    
    ArrayList<Color> colores= new ArrayList<>();
    ArrayList<Integer> vertices = new ArrayList<>();
    /**
     * Creates new form SeleccionarEstrella
     */
    public EstrellaEnEstrella() {
        initComponents();
        lblColor1.setBackground(Color.white);
        lblColor2.setBackground(Color.white);
        lblColor3.setBackground(Color.white);
        lblColor4.setBackground(Color.white);
        lblColor5.setBackground(Color.white);
        txtVertices1.setText(String.valueOf(slVertices1.getValue()));
        txtVertices2.setText(String.valueOf(slVertices2.getValue()));
        txtVertices3.setText(String.valueOf(slVertices3.getValue()));
        txtVertices4.setText(String.valueOf(slVertices4.getValue()));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ccColor = new javax.swing.JColorChooser();
        lblCuadrante = new javax.swing.JLabel();
        lblVertices = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        slVertices2 = new javax.swing.JSlider();
        lblCuadrante1 = new javax.swing.JLabel();
        lblCuadrante2 = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        slVertices1 = new javax.swing.JSlider();
        lblCuadrante4 = new javax.swing.JLabel();
        slVertices3 = new javax.swing.JSlider();
        slVertices4 = new javax.swing.JSlider();
        txtVertices1 = new javax.swing.JTextField();
        txtVertices2 = new javax.swing.JTextField();
        txtVertices3 = new javax.swing.JTextField();
        txtVertices4 = new javax.swing.JTextField();
        lblColor1 = new javax.swing.JLabel();
        lblColor2 = new javax.swing.JLabel();
        lblColor3 = new javax.swing.JLabel();
        lblColor4 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        lblTodosColores = new javax.swing.JLabel();
        lblColor5 = new javax.swing.JLabel();
        slVertices5 = new javax.swing.JSlider();
        txtVertices5 = new javax.swing.JTextField();
        btnRand = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(652, 550));

        lblCuadrante.setText("Cuadrante 1");

        lblVertices.setText("Ingrese la cantidad de vertices");

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        slVertices2.setMinimum(1);
        slVertices2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slVertices2StateChanged(evt);
            }
        });

        lblCuadrante1.setText("Cuadrante 2");

        lblCuadrante2.setText("Cuadrante 3");

        lblColor.setText("Color");

        slVertices1.setMinimum(1);
        slVertices1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slVertices1StateChanged(evt);
            }
        });

        lblCuadrante4.setText("Cuadrante 4");

        slVertices3.setMinimum(1);
        slVertices3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slVertices3StateChanged(evt);
            }
        });

        slVertices4.setMinimum(1);
        slVertices4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slVertices4StateChanged(evt);
            }
        });

        txtVertices1.setEnabled(false);

        txtVertices2.setEnabled(false);

        txtVertices3.setEnabled(false);

        txtVertices4.setEnabled(false);

        lblColor1.setText("Color");
        lblColor1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblColor1.setMaximumSize(new java.awt.Dimension(35, 20));
        lblColor1.setMinimumSize(new java.awt.Dimension(35, 20));
        lblColor1.setOpaque(true);
        lblColor1.setPreferredSize(new java.awt.Dimension(35, 20));
        lblColor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblColor1MouseClicked(evt);
            }
        });

        lblColor2.setText("Color");
        lblColor2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblColor2.setMaximumSize(new java.awt.Dimension(35, 20));
        lblColor2.setMinimumSize(new java.awt.Dimension(35, 20));
        lblColor2.setOpaque(true);
        lblColor2.setPreferredSize(new java.awt.Dimension(35, 20));
        lblColor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblColor2MouseClicked(evt);
            }
        });

        lblColor3.setText("Color");
        lblColor3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblColor3.setMaximumSize(new java.awt.Dimension(35, 20));
        lblColor3.setMinimumSize(new java.awt.Dimension(35, 20));
        lblColor3.setOpaque(true);
        lblColor3.setPreferredSize(new java.awt.Dimension(35, 20));
        lblColor3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblColor3MouseClicked(evt);
            }
        });

        lblColor4.setText("Color");
        lblColor4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblColor4.setMaximumSize(new java.awt.Dimension(35, 20));
        lblColor4.setMinimumSize(new java.awt.Dimension(35, 20));
        lblColor4.setOpaque(true);
        lblColor4.setPreferredSize(new java.awt.Dimension(35, 20));
        lblColor4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblColor4MouseClicked(evt);
            }
        });

        btnReset.setText("Reestablecer");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblTodosColores.setText("Todos ");

        lblColor5.setText("Color");
        lblColor5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblColor5.setMaximumSize(new java.awt.Dimension(35, 20));
        lblColor5.setMinimumSize(new java.awt.Dimension(35, 20));
        lblColor5.setOpaque(true);
        lblColor5.setPreferredSize(new java.awt.Dimension(35, 20));
        lblColor5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblColor5MouseClicked(evt);
            }
        });

        slVertices5.setMinimum(1);
        slVertices5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slVertices5StateChanged(evt);
            }
        });

        txtVertices5.setEnabled(false);

        btnRand.setText("Color Rand");
        btnRand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ccColor, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblColor)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCuadrante1)
                            .addComponent(lblCuadrante4)
                            .addComponent(lblCuadrante2)
                            .addComponent(lblCuadrante)
                            .addComponent(lblTodosColores))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblColor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblColor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblColor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblColor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblColor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slVertices3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVertices3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slVertices4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVertices4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slVertices1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVertices1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblVertices)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slVertices2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVertices2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slVertices5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVertices5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVertices)
                    .addComponent(lblColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuadrante)
                    .addComponent(slVertices1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVertices1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrar))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slVertices2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCuadrante1)
                        .addComponent(txtVertices2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblColor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuadrante2)
                    .addComponent(slVertices3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVertices3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRand))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuadrante4)
                    .addComponent(slVertices4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVertices4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblColor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(slVertices5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtVertices5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReset))
                    .addComponent(lblTodosColores))
                .addGap(18, 47, Short.MAX_VALUE)
                .addComponent(ccColor, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        colores.clear();
        colores.add(lblColor1.getBackground());
        colores.add(lblColor2.getBackground());
        colores.add(lblColor3.getBackground());
        colores.add(lblColor4.getBackground());
        
        vertices.clear();
        vertices.add(slVertices1.getValue());
        vertices.add(slVertices2.getValue());
        vertices.add(slVertices3.getValue());
        vertices.add(slVertices4.getValue());
        MostrarEstrellaEnEstrella mostrarEstrellaEnEstrella = new MostrarEstrellaEnEstrella(colores,vertices);
        mostrarEstrellaEnEstrella.setVisible(true);
        
    }//GEN-LAST:event_btnMostrarActionPerformed

    
    private void slVertices2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slVertices2StateChanged
        // TODO add your handling code here:
        txtVertices2.setText(String.valueOf(slVertices2.getValue()));
    }//GEN-LAST:event_slVertices2StateChanged

    private void slVertices1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slVertices1StateChanged
        // TODO add your handling code here:
        txtVertices1.setText(String.valueOf(slVertices1.getValue()));
    }//GEN-LAST:event_slVertices1StateChanged

    private void slVertices3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slVertices3StateChanged
        // TODO add your handling code here:
        txtVertices3.setText(String.valueOf(slVertices3.getValue()));
    }//GEN-LAST:event_slVertices3StateChanged

    private void slVertices4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slVertices4StateChanged
        // TODO add your handling code here:
        txtVertices4.setText(String.valueOf(slVertices4.getValue()));
    }//GEN-LAST:event_slVertices4StateChanged

    private void lblColor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblColor1MouseClicked
        // TODO add your handling code here:
        lblColor1.setBackground(ccColor.getColor());
    }//GEN-LAST:event_lblColor1MouseClicked

    private void lblColor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblColor2MouseClicked
        // TODO add your handling code here:
        lblColor2.setBackground(ccColor.getColor());
    }//GEN-LAST:event_lblColor2MouseClicked

    private void lblColor3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblColor3MouseClicked
        // TODO add your handling code here:
        lblColor3.setBackground(ccColor.getColor());
    }//GEN-LAST:event_lblColor3MouseClicked

    private void lblColor4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblColor4MouseClicked
        // TODO add your handling code here:
        lblColor4.setBackground(ccColor.getColor());
    }//GEN-LAST:event_lblColor4MouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        slVertices1.setValue(50);
        slVertices2.setValue(50);
        slVertices3.setValue(50);
        slVertices4.setValue(50);
        lblColor1.setBackground(Color.white);
        lblColor2.setBackground(Color.white);
        lblColor3.setBackground(Color.white);
        lblColor4.setBackground(Color.white);
    }//GEN-LAST:event_btnResetActionPerformed

    private void slVertices5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slVertices5StateChanged
        // TODO add your handling code here:
       slVertices1.setValue(slVertices5.getValue());
       slVertices2.setValue(slVertices5.getValue());
       slVertices3.setValue(slVertices5.getValue());
       slVertices4.setValue(slVertices5.getValue());
        
        
//        slVertices1.
    }//GEN-LAST:event_slVertices5StateChanged

    private void lblColor5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblColor5MouseClicked
        // TODO add your handling code here:
        lblColor1.setBackground(ccColor.getColor());
        lblColor2.setBackground(ccColor.getColor());
        lblColor3.setBackground(ccColor.getColor());
        lblColor4.setBackground(ccColor.getColor());
        lblColor5.setBackground(ccColor.getColor());
    }//GEN-LAST:event_lblColor5MouseClicked

    public int getRandomNumber(int min, int max) {
    return (int) ((Math.random() * (max - min)) + min);
    }
    
    private void btnRandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandActionPerformed
        // TODO add your handling code here:
        lblColor1.setBackground(new Color(getRandomNumber(0, 255),getRandomNumber(0, 255),getRandomNumber(0, 255)));
        lblColor2.setBackground(new Color(getRandomNumber(0, 255),getRandomNumber(0, 255),getRandomNumber(0, 255)));
        lblColor3.setBackground(new Color(getRandomNumber(0, 255),getRandomNumber(0, 255),getRandomNumber(0, 255)));
        lblColor4.setBackground(new Color(getRandomNumber(0, 255),getRandomNumber(0, 255),getRandomNumber(0, 255)));
    }//GEN-LAST:event_btnRandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstrellaEnEstrella.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstrellaEnEstrella.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstrellaEnEstrella.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstrellaEnEstrella.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstrellaEnEstrella().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnRand;
    private javax.swing.JButton btnReset;
    private javax.swing.JColorChooser ccColor;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblColor1;
    private javax.swing.JLabel lblColor2;
    private javax.swing.JLabel lblColor3;
    private javax.swing.JLabel lblColor4;
    private javax.swing.JLabel lblColor5;
    private javax.swing.JLabel lblCuadrante;
    private javax.swing.JLabel lblCuadrante1;
    private javax.swing.JLabel lblCuadrante2;
    private javax.swing.JLabel lblCuadrante4;
    private javax.swing.JLabel lblTodosColores;
    private javax.swing.JLabel lblVertices;
    private javax.swing.JSlider slVertices1;
    private javax.swing.JSlider slVertices2;
    private javax.swing.JSlider slVertices3;
    private javax.swing.JSlider slVertices4;
    private javax.swing.JSlider slVertices5;
    private javax.swing.JTextField txtVertices1;
    private javax.swing.JTextField txtVertices2;
    private javax.swing.JTextField txtVertices3;
    private javax.swing.JTextField txtVertices4;
    private javax.swing.JTextField txtVertices5;
    // End of variables declaration//GEN-END:variables
}
